version: "3"
services:
  movie-rating-mongodb:
    image: mongo:latest
    container_name: "movie-rating-mongodb"
    ports:
      - 27017:27017
  movie-rating-project-backend:
    image: movie-rating-project-backend:latest
    container_name: movie-rating-project-backend
    ports:
      - 8080:8080
    links:
      - movie-rating-mongodb